### ISSUE TITLE
Will the list continue to be updated? 

### ISSUE THREAD

**Issue by TaoCesc** [thuiar/OKD-Reading-List#8]
Hello, I like your work (ADB) very much and this reading list has helped me a lot.
Will you continue to update the latest research results in this field? I saw several new papers on this year’s EMNLP, such as 
“Out-of-Scope Intent Detection with Self-Supervision and Discriminative Training”
Thank you very much!

**Comment by HanleiZhang** [comment]
Hi! Thanks for your attention in this project! We will continue to update the latest research in this field and have updated serveral papers in ACL 2021 and EMNLP 2021 (including the paper you mentioned). If there are any missing papers, please tell us or pull request~ Thanks!

**Comment by TaoCesc** [comment]
> 

Thank you again for your efforts on this work. I am very sorry because I got the title of the paper wrong. I found some potentially related works on EMNLP 2021. **"Contrastive Out-of-Distribution Detection for Pretrained Transformers"**,  **"Types of Out-of-Distribution Texts and How to Detect Them"**,  **"GOLD: Improving Out-of-Scope Detection in Dialogues using Data Augmentation"**.

**Comment by HanleiZhang** [comment]
We have added your mentioned three papers in our reading list! Thank you very much for your contribution!
